[build]
  command = "npm run build"
  publish = "project/dist"

[build.environment]
  NODE_VERSION = "18"

# Handle frontend routing (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
